// users
export const LOAD_USERS_PENDING = 'LOAD_USERS_PENDING'
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
export const LOAD_USERS_FAILED = 'LOAD_USERS_FAILED'
export const ADD_USER = 'ADD_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const DELETE_USER = 'DELETE_USER'
// currentUser
export const LOAD_USER_PENDING = 'LOAD_USER_PENDING'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAILED = 'LOAD_USER_FAILED'
