export const LOAD_USERS = 'LOAD_USERS'
export const ADD_USER = 'ADD_USER'
export const GET_USER = 'GET_USER'
export const CHANGE_ACTIVE_FORM_STAGE = 'CHANGE_ACTIVE_FORM_STAGE'
export const LOAD_AVATAR = 'LOAD_AVATAR'
